import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import AppLayout from "./AppLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body>
        <StoreProvider>
          <AppLayout>
            {children}
          </AppLayout>
        </StoreProvider>
        </body>
      </html>
    );
  }

