import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import NavigationHeader from "@/components/NavigationHeader";
import FooterPage from "@/components/FooterPage";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body>
        <NavigationHeader />
        <main>
        <StoreProvider>
            {children}
        </StoreProvider>
        </main>
        <FooterPage/>
        </body>
      </html>
    );
  }

